name: GitHub Actions (build master)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish to NuGet
      env:
        nuget_token: ${{ secrets.NUGETJXF }}
      run: dotnet nuget push ./**/Release/*.nupkg -k $nuget_token -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
